<?php

namespace App\Services;

use App\Enums\ApplicationDeploymentStatus;
use App\Enums\BuildPackTypes;
use App\Enums\StaticImageTypes;
use App\Models\Application;
use App\Models\ApplicationDeploymentQueue;
use App\Models\Environment;
use App\Models\GithubApp;
use App\Models\Project;
use App\Models\Server;
use App\Models\StandaloneDocker;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;
use RuntimeException;
use Spatie\Url\Url;
use Throwable;
use Visus\Cuid2\Cuid2;

class McpRepositoryDeploymentService
{
    /**
     * @var array<int, string>
     */
    private const SUPPORTED_BUILD_PACKS = [
        BuildPackTypes::NIXPACKS->value,
        BuildPackTypes::RAILPACK->value,
        BuildPackTypes::STATIC->value,
        BuildPackTypes::DOCKERFILE->value,
    ];

    /**
     * @var array<int, string>
     */
    private const TERMINAL_OPERATOR_STATUSES = [
        'recorded',
        'verification_failed',
        'retry_queued',
        'no_retry',
        'max_attempts_reached',
        'ineligible',
        'superseded',
    ];

    public function __construct(
        private GithubRepositoryInspectionService $inspectionService,
        private DeploymentAdvisorService $deploymentAdvisorService,
        private ApplicationDeploymentOperatorService $applicationDeploymentOperatorService,
        private RepositoryDeploymentResultWaiter $resultWaiter,
    ) {}

    /**
     * @param  array<string, mixed>  $arguments
     * @return array<string, mixed>
     */
    public function deploy(int $teamId, array $arguments): array
    {
        $githubApp = $this->resolveGithubApp($teamId, $arguments);
        if (! $githubApp) {
            throw new RuntimeException('GitHub source not found for this team.');
        }

        $project = Project::query()
            ->where('team_id', $teamId)
            ->where('uuid', $arguments['project_uuid'])
            ->first();

        if (! $project) {
            throw new RuntimeException('Project not found.');
        }

        $environment = $this->resolveEnvironment($project, $arguments);
        $server = Server::query()
            ->where('team_id', $teamId)
            ->where('uuid', $arguments['server_uuid'])
            ->first();

        if (! $server) {
            throw new RuntimeException('Server not found.');
        }

        $destination = $this->resolveDestination($server, $arguments);

        $inspection = $this->inspectionService->inspectPrivateRepository(
            githubApp: $githubApp,
            owner: $arguments['repo_owner'],
            repo: $arguments['repo_name'],
            branch: $arguments['branch'],
            selection: $this->selectionHints($arguments),
        );

        $analysis = $this->deploymentAdvisorService->recommend($inspection);
        $recommendation = $this->resolveRecommendation($analysis, $arguments);

        if (! in_array($recommendation['build_pack'], self::SUPPORTED_BUILD_PACKS, true)) {
            throw new RuntimeException(sprintf(
                'This deploy tool currently supports %s repository apps. Recommended build pack [%s] is not supported yet.',
                implode(', ', self::SUPPORTED_BUILD_PACKS),
                $recommendation['build_pack'] ?? 'unknown'
            ));
        }

        $repositoryMetadata = $this->fetchRepositoryMetadata($githubApp, $arguments['repo_owner'], $arguments['repo_name']);
        $applicationUuid = (string) new Cuid2;
        $domains = $this->resolvedDomains(
            server: $server,
            applicationUuid: $applicationUuid,
            domainOverride: $arguments['domain_override'] ?? null,
            autogenerateDomain: (bool) ($arguments['autogenerate_domain'] ?? true),
        );

        $this->ensureDomainConflictsAreSafe($teamId, $server, $domains);

        $application = $this->createApplication(
            applicationUuid: $applicationUuid,
            githubApp: $githubApp,
            environment: $environment,
            destination: $destination,
            repositoryMetadata: $repositoryMetadata,
            arguments: $arguments,
            recommendation: $recommendation,
            domains: $domains,
        );

        $operatorSupport = $this->enableOperatorWhenSupported($application);
        $application->refresh();
        $application->isConfigurationChanged(true);

        $deploymentUuid = (string) new Cuid2;
        $queueResult = queue_application_deployment(
            application: $application,
            deployment_uuid: $deploymentUuid,
            no_questions_asked: true,
            is_api: true,
        );

        $deployment = ApplicationDeploymentQueue::query()
            ->where('deployment_uuid', $deploymentUuid)
            ->first();

        $waited = false;
        $waitTimedOut = false;

        if (($arguments['wait_for_result'] ?? false) && $deployment) {
            $waited = true;
            $deployment = $this->resultWaiter->wait($deployment);
            $waitTimedOut = ! $this->isTerminalDeployment($deployment);
        }

        return [
            'source' => [
                'uuid' => $githubApp->uuid,
                'name' => $githubApp->name,
                'is_system_wide' => (bool) $githubApp->is_system_wide,
            ],
            'repository' => [
                'owner' => $arguments['repo_owner'],
                'repo' => $arguments['repo_name'],
                'branch' => $arguments['branch'],
                'id' => data_get($repositoryMetadata, 'id'),
            ],
            'target' => [
                'project_uuid' => $project->uuid,
                'environment_uuid' => $environment->uuid,
                'server_uuid' => $server->uuid,
                'destination_uuid' => $destination->uuid,
            ],
            'analysis' => [
                'fingerprint' => data_get($inspection, 'meta.inspection_fingerprint'),
                'recommendation' => Arr::only($recommendation, [
                    'build_pack',
                    'install_command',
                    'build_command',
                    'start_command',
                    'port',
                    'base_directory',
                    'publish_directory',
                    'is_static',
                    'confidence',
                    'rationale',
                    'caveats',
                    'source',
                ]),
            ],
            'application' => [
                'uuid' => $application->uuid,
                'name' => $application->name,
                'build_pack' => $application->build_pack,
                'is_static' => (bool) data_get($application, 'settings.is_static', false),
                'git_repository' => $application->git_repository,
                'git_branch' => $application->git_branch,
                'fqdn' => $application->fqdn,
                'domains' => $this->domainList((string) $application->fqdn),
                'operator_enabled' => (bool) data_get($application, 'settings.is_deployment_operator_enabled', false),
                'operator_support' => $operatorSupport,
            ],
            'deployment' => [
                'queue_status' => $queueResult['status'] ?? null,
                'queue_message' => $queueResult['message'] ?? null,
                'deployment_uuid' => $deployment?->deployment_uuid ?? ($queueResult['deployment_uuid'] ?? null),
                'status' => $deployment?->status,
                'operator_status' => $deployment?->operator_status,
                'operator_verification' => $deployment?->operator_verification,
                'finished_at' => $deployment?->finished_at?->toISOString(),
                'waited' => $waited,
                'wait_timed_out' => $waitTimedOut,
            ],
            'result' => $this->resultSummary($application, $deployment, $queueResult, $waitTimedOut),
        ];
    }

    /**
     * @param  array<string, mixed>  $arguments
     */
    private function resolveGithubApp(int $teamId, array $arguments): ?GithubApp
    {
        $identifier = $arguments['github_app_uuid'] ?? $arguments['source_uuid'] ?? null;
        $numericIdentifier = $arguments['github_app_id'] ?? $arguments['source_id'] ?? null;

        return GithubApp::query()
            ->where(function ($query) use ($teamId) {
                $query->where('team_id', $teamId)
                    ->orWhere('is_system_wide', true);
            })
            ->when(filled($identifier), fn ($query) => $query->where('uuid', $identifier))
            ->when(blank($identifier) && filled($numericIdentifier), fn ($query) => $query->whereKey((int) $numericIdentifier))
            ->first();
    }

    /**
     * @param  array<string, mixed>  $arguments
     */
    private function resolveEnvironment(Project $project, array $arguments): Environment
    {
        $environment = null;

        if (filled($arguments['environment_uuid'] ?? null)) {
            $environment = $project->environments()
                ->where('uuid', $arguments['environment_uuid'])
                ->first();
        }

        if (! $environment && filled($arguments['environment_name'] ?? null)) {
            $environment = $project->environments()
                ->where('name', $arguments['environment_name'])
                ->first();
        }

        if (! $environment) {
            throw new RuntimeException('Environment not found.');
        }

        return $environment;
    }

    /**
     * @param  array<string, mixed>  $arguments
     */
    private function resolveDestination(Server $server, array $arguments): StandaloneDocker
    {
        $destinations = $server->standaloneDockers()->get();

        if ($destinations->count() === 0) {
            throw new RuntimeException('Server has no destinations.');
        }

        if ($destinations->count() > 1 && blank($arguments['destination_uuid'] ?? null)) {
            throw new RuntimeException('Server has multiple destinations and you do not set destination_uuid.');
        }

        if (blank($arguments['destination_uuid'] ?? null)) {
            /** @var StandaloneDocker $destination */
            $destination = $destinations->first();

            return $destination;
        }

        /** @var StandaloneDocker|null $destination */
        $destination = $destinations->firstWhere('uuid', $arguments['destination_uuid']);

        if (! $destination) {
            throw new RuntimeException('Provided destination_uuid does not belong to the specified server.');
        }

        return $destination;
    }

    /**
     * @param  array<string, mixed>  $arguments
     * @return array<string, mixed>
     */
    private function selectionHints(array $arguments): array
    {
        return [
            'build_pack' => $arguments['desired_build_pack'] ?? null,
            'base_directory' => $arguments['base_directory'] ?? '/',
            'port' => $arguments['desired_port'] ?? null,
            'is_static' => filter_var($arguments['is_static'] ?? false, FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
        ];
    }

    /**
     * @param  array<string, mixed>  $analysis
     * @param  array<string, mixed>  $arguments
     * @return array<string, mixed>
     */
    private function resolveRecommendation(array $analysis, array $arguments): array
    {
        $recommendation = data_get($analysis, 'recommendation', []);

        $buildPack = $arguments['desired_build_pack']
            ?? data_get($recommendation, 'build_pack')
            ?? BuildPackTypes::NIXPACKS->value;
        $isStatic = filter_var(
            $arguments['is_static'] ?? data_get($recommendation, 'is_static', false),
            FILTER_VALIDATE_BOOL,
            FILTER_NULL_ON_FAILURE
        ) ?? false;
        if ($buildPack === BuildPackTypes::STATIC->value) {
            $isStatic = true;
        }
        $port = $arguments['desired_port']
            ?? data_get($recommendation, 'port')
            ?? ($isStatic ? 80 : 3000);

        return [
            'build_pack' => $buildPack,
            'install_command' => data_get($recommendation, 'install_command'),
            'build_command' => data_get($recommendation, 'build_command'),
            'start_command' => data_get($recommendation, 'start_command'),
            'port' => (int) $port,
            'base_directory' => data_get($recommendation, 'base_directory', $arguments['base_directory'] ?? '/'),
            'publish_directory' => data_get($recommendation, 'publish_directory'),
            'is_static' => $isStatic,
            'confidence' => data_get($recommendation, 'confidence'),
            'rationale' => data_get($recommendation, 'rationale'),
            'caveats' => data_get($recommendation, 'caveats', []),
            'source' => data_get($recommendation, 'source'),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function fetchRepositoryMetadata(GithubApp $githubApp, string $owner, string $repo): array
    {
        $token = generateGithubInstallationToken($githubApp);
        if (! $token) {
            throw new RuntimeException('Failed to generate Github App token.');
        }

        $response = Http::GitHub($githubApp->api_url, $token)
            ->timeout(20)
            ->retry(3, 200, throw: false)
            ->get("/repos/{$owner}/{$repo}");

        if (in_array($response->status(), [403, 404], true)) {
            throw new RuntimeException('Repository not found or not accessible by the GitHub App.');
        }

        if (! $response->successful()) {
            throw new RuntimeException('Failed to verify repository access: '.($response->json()['message'] ?? 'Unknown error'));
        }

        $metadata = $response->json();

        return is_array($metadata) ? $metadata : [];
    }

    /**
     * @return array<int, string>
     */
    private function resolvedDomains(Server $server, string $applicationUuid, ?string $domainOverride, bool $autogenerateDomain): array
    {
        $domains = collect();

        if ($autogenerateDomain) {
            $domains->push(generateUrl($server, $applicationUuid));
        }

        if (filled($domainOverride)) {
            $domains->push($this->normalizeDomain((string) $domainOverride));
        }

        return $domains
            ->filter()
            ->unique()
            ->values()
            ->all();
    }

    /**
     * @param  array<int, string>  $domains
     */
    private function ensureDomainConflictsAreSafe(int $teamId, Server $server, array $domains): void
    {
        if ($domains === [] || ! $server->isProxyShouldRun()) {
            return;
        }

        $result = checkIfDomainIsAlreadyUsedViaAPI($domains, $teamId);
        if (isset($result['error'])) {
            throw new RuntimeException((string) $result['error']);
        }

        if (($result['hasConflicts'] ?? false) === true) {
            $message = collect($result['conflicts'] ?? [])
                ->map(fn (array $conflict): string => (string) data_get($conflict, 'message'))
                ->filter()
                ->implode(' | ');

            throw new RuntimeException($message !== ''
                ? 'Domain conflicts detected: '.$message
                : 'Domain conflicts detected.');
        }
    }

    /**
     * @param  array<string, mixed>  $repositoryMetadata
     * @param  array<string, mixed>  $arguments
     * @param  array<string, mixed>  $recommendation
     * @param  array<int, string>  $domains
     */
    private function createApplication(
        string $applicationUuid,
        GithubApp $githubApp,
        Environment $environment,
        StandaloneDocker $destination,
        array $repositoryMetadata,
        array $arguments,
        array $recommendation,
        array $domains,
    ): Application {
        $repositoryPath = trim($arguments['repo_owner'].'/'.$arguments['repo_name'], '/');
        $application = new Application;
        $application->fill([
            'uuid' => $applicationUuid,
            'name' => (string) ($arguments['name'] ?? generate_application_name($repositoryPath, $arguments['branch'])),
            'description' => $arguments['description'] ?? "MCP deploy for {$repositoryPath}@{$arguments['branch']}",
            'fqdn' => implode(',', $domains),
            'git_repository' => $repositoryPath,
            'git_branch' => $arguments['branch'],
            'build_pack' => $recommendation['build_pack'],
            'install_command' => $recommendation['install_command'],
            'build_command' => $recommendation['build_command'],
            'start_command' => $recommendation['start_command'],
            'ports_exposes' => (string) ($recommendation['is_static'] ? 80 : $recommendation['port']),
            'base_directory' => $recommendation['base_directory'] ?? '/',
            'publish_directory' => $recommendation['publish_directory'],
            'static_image' => StaticImageTypes::NGINX_ALPINE->value,
            'destination_id' => $destination->id,
            'destination_type' => $destination->getMorphClass(),
            'environment_id' => $environment->id,
            'source_type' => $githubApp->getMorphClass(),
            'source_id' => $githubApp->id,
            'repository_project_id' => data_get($repositoryMetadata, 'id'),
        ]);
        $application->save();

        $application->refresh();
        $application->settings->forceFill([
            'is_static' => (bool) $recommendation['is_static'],
        ])->save();

        return $application->fresh(['settings', 'destination.server', 'environment.project']);
    }

    /**
     * @return array{enabled: bool, reason: string}
     */
    private function enableOperatorWhenSupported(Application $application): array
    {
        $application = $application->fresh(['settings', 'destination.server']);
        $settings = $application->settings;
        if (! $settings) {
            return ['enabled' => false, 'reason' => 'missing_settings'];
        }

        $originalValue = (bool) $settings->is_deployment_operator_enabled;
        $settings->setAttribute('is_deployment_operator_enabled', true);

        $deployment = new ApplicationDeploymentQueue([
            'application_id' => $application->id,
            'server_id' => $application->destination->server_id,
            'destination_id' => $application->destination_id,
            'pull_request_id' => 0,
            'status' => ApplicationDeploymentStatus::QUEUED->value,
        ]);
        $deployment->setRelation('application', $application);

        $eligibility = $this->applicationDeploymentOperatorService->eligibility($deployment);

        if (($eligibility['eligible'] ?? false) === true) {
            $settings->forceFill(['is_deployment_operator_enabled' => true])->save();

            return ['enabled' => true, 'reason' => (string) ($eligibility['reason'] ?? 'supported')];
        }

        $settings->setAttribute('is_deployment_operator_enabled', $originalValue);

        return ['enabled' => false, 'reason' => (string) ($eligibility['reason'] ?? 'unsupported')];
    }

    /**
     * @param  array<string, mixed>  $queueResult
     * @return array<string, mixed>
     */
    private function resultSummary(Application $application, ?ApplicationDeploymentQueue $deployment, array $queueResult, bool $waitTimedOut): array
    {
        $state = 'pending';
        $reason = $queueResult['message'] ?? 'Deployment queued.';

        if (($queueResult['status'] ?? null) === 'queue_full') {
            $state = 'failed';
        }

        if ($deployment) {
            if (in_array($deployment->status, [ApplicationDeploymentStatus::FAILED->value, ApplicationDeploymentStatus::CANCELLED_BY_USER->value], true)) {
                $state = 'failed';
                $reason = 'Deployment failed before becoming ready.';
            } elseif ($deployment->status === ApplicationDeploymentStatus::FINISHED->value) {
                if (in_array((string) $deployment->operator_status, ['recorded'], true)) {
                    $state = 'ready';
                    $reason = 'Deployment finished and verification passed.';
                } elseif (in_array((string) $deployment->operator_status, ['verification_failed', 'no_retry', 'max_attempts_reached'], true)) {
                    $state = 'failed';
                    $reason = 'Deployment finished but verification or remediation failed.';
                } elseif (filled($deployment->operator_status)) {
                    $state = 'pending';
                    $reason = 'Deployment finished; operator follow-up is still pending.';
                } else {
                    $state = 'ready';
                    $reason = 'Deployment finished.';
                }
            }
        }

        if ($waitTimedOut && $state === 'pending') {
            $reason = 'Timed out waiting for deployment result.';
        }

        return [
            'state' => $state,
            'url' => $this->preferredUrl($application, $deployment, $state),
            'urls' => $this->domainList((string) $application->fqdn),
            'reason' => $reason,
        ];
    }

    private function preferredUrl(Application $application, ?ApplicationDeploymentQueue $deployment, string $state): ?string
    {
        if ($state === 'ready' && $deployment) {
            $passedCustomDomain = collect(data_get($deployment->operator_verification, 'custom_domains.domains', []))
                ->first(fn (array $domain): bool => ($domain['result'] ?? null) === 'passed');

            if ($passedCustomDomain) {
                return (string) data_get($passedCustomDomain, 'domain');
            }

            $verifiedTarget = data_get($deployment->operator_verification, 'target');
            if (filled($verifiedTarget)) {
                return (string) $verifiedTarget;
            }
        }

        return $this->domainList((string) $application->fqdn)[0] ?? null;
    }

    /**
     * @return array<int, string>
     */
    private function domainList(string $fqdn): array
    {
        return collect(explode(',', $fqdn))
            ->map(fn (string $domain): string => trim($domain))
            ->filter()
            ->values()
            ->all();
    }

    private function normalizeDomain(string $domain): string
    {
        try {
            $url = Url::fromString(trim($domain));

            if (! in_array($url->getScheme(), ['http', 'https'], true)) {
                throw new RuntimeException('Only http and https domains are supported.');
            }

            if ($url->getHost() === '' || $url->getPort() !== null || $url->getPath() !== '' && $url->getPath() !== '/') {
                throw new RuntimeException('Domain override must be a plain absolute host URL without custom port or path.');
            }

            return rtrim((string) $url, '/');
        } catch (Throwable $exception) {
            if ($exception instanceof RuntimeException) {
                throw $exception;
            }

            throw new RuntimeException('Domain override must be a valid absolute URL.');
        }
    }

    private function isTerminalDeployment(ApplicationDeploymentQueue $deployment): bool
    {
        if (in_array($deployment->status, [ApplicationDeploymentStatus::FAILED->value, ApplicationDeploymentStatus::CANCELLED_BY_USER->value], true)) {
            return true;
        }

        if ($deployment->status !== ApplicationDeploymentStatus::FINISHED->value) {
            return false;
        }

        $operatorEnabled = (bool) data_get($deployment, 'application.settings.is_deployment_operator_enabled', false);
        if (! $operatorEnabled) {
            return true;
        }

        return in_array((string) $deployment->operator_status, self::TERMINAL_OPERATOR_STATUSES, true);
    }
}
